---

- name: install HTTPS transport for APT
  apt: pkg=apt-transport-https state=installed update_cache=yes cache_valid_time=86400

- name: add Docker apt key
  apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80 state=present

- name: add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present
  register: repo

- name: install docker package
  apt: name=docker-engine update_cache={{ repo.changed }}
  notify: restart docker

- name: enable docker service
  service: name=docker enabled=yes
